create table if not exists public.fitmind_workout_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_key text not null,
  summary_date date not null,
  day_code text not null,
  completion_rate integer not null default 0,
  exercise_done integer not null default 0,
  exercise_total integer not null default 0,
  set_done integer not null default 0,
  set_total integer not null default 0,
  search_count integer not null default 0,
  workout_elapsed_sec integer not null default 0,
  anxiety_score integer not null default 3,
  saved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, session_key)
);

create index if not exists idx_fitmind_workout_summaries_user_saved_at
  on public.fitmind_workout_summaries (user_id, saved_at desc);

alter table public.fitmind_workout_summaries enable row level security;

drop policy if exists "fitmind summaries select own" on public.fitmind_workout_summaries;
create policy "fitmind summaries select own"
  on public.fitmind_workout_summaries
  for select
  using (auth.uid() = user_id);

drop policy if exists "fitmind summaries insert own" on public.fitmind_workout_summaries;
create policy "fitmind summaries insert own"
  on public.fitmind_workout_summaries
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "fitmind summaries update own" on public.fitmind_workout_summaries;
create policy "fitmind summaries update own"
  on public.fitmind_workout_summaries
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "fitmind summaries delete own" on public.fitmind_workout_summaries;
create policy "fitmind summaries delete own"
  on public.fitmind_workout_summaries
  for delete
  using (auth.uid() = user_id);

create or replace function public.fitmind_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_fitmind_workout_summaries_updated_at on public.fitmind_workout_summaries;
create trigger trg_fitmind_workout_summaries_updated_at
before update on public.fitmind_workout_summaries
for each row
execute function public.fitmind_set_updated_at();
